const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,f);
const A=require('../src/planning/routeAssistant/index.ts');
const H=require('../src/editor/history.ts');
const R=require('../src/planning/routeAI/resolve.ts');
const T=require('../src/planning/routeAI/types.ts');
const {RouteAIController,quickPrompts,friendlyError}=require('../src/planning/routeAI/controller.ts');
const {mockAdapter}=require('../src/planning/routeAI/testing/mockAdapter.ts');
function fixture(decisions=[],availability='AVAILABLE'){
  const position=(x,y)=>({space:'stage',x,y,z:0});
  const stage={schemaVersion:7,coordinateSystem:'inches',stage:{width:300,depth:240},objects:[{id:'start',type:'start',position:position(20,100),rotation:0,geometry:{width:12,depth:12,height:0}}]};
  const plan=require('../src/planning/model.ts').createPlan();plan.route=require('../src/planning/route.ts').createRoute('r');
  plan.route.positions=[['W1',90,100],['W2',150,60],['W3',240,100]].map(([id,x,y])=>({id,label:id,position:position(x,y),visibleTargetIds:[],engagedTargetIds:[]}));
  plan.route.engagementRules={...require('../src/planning/engagements.ts').defaultEngagementRules(),firingAreas:[{id:'goal',vertices:[{x:235,y:95},{x:245,y:95},{x:245,y:105},{x:235,y:105}]}]};
  const mock=mockAdapter(decisions,availability);
  const f={stage,plan,h:{document:H.history({stage,plan}),assistantChanges:[]},selected:undefined,mock};
  f.context=()=>A.createRouteAssistantContext(f.h.document.present.stage,f.h.document.present.plan,{selectedWaypointId:f.selected,solverResult:f.solverResult});
  f.controller=new RouteAIController(mock.adapter,'stage-s',f.context,()=>f.h,s=>{f.state=s;},'mock');
  return f;
}
const move={intent:'MOVE_WAYPOINT',waypointReference:'waypoint 2',distanceValue:2,distanceUnit:'yards',direction:'left'};
for(const state of ['AVAILABLE','UNSUPPORTED_DEVICE','APPLE_INTELLIGENCE_NOT_ENABLED','MODEL_NOT_READY','UNSUPPORTED_OS','NATIVE_UNAVAILABLE','UNKNOWN'])test('availability '+state,async()=>{
  const f=fixture([],state);await f.controller.initialize();assert.equal(f.state.availability,state);if(state!=='AVAILABLE'){await f.controller.send('How long?');assert.equal(f.mock.calls.filter(c=>c.method==='interpret').length,0);}
});
test('unit conversion is deterministic',()=>{assert.equal(R.inches(2,'yards'),72);assert.equal(R.inches(3,'feet'),36);assert.equal(R.inches(4,'inches'),4);assert.throws(()=>R.inches(2,'meters'));assert.throws(()=>R.inches(Infinity,'yd'));});
for(const [reference,expected] of [['waypoint 2','W2'],['the second waypoint','W2'],['the last waypoint','W3'],['W1','W1']])test('reference '+reference,()=>{assert.deepEqual(R.waypointCandidates(fixture().context(),reference),[expected]);});
test('selected point and ambiguity are resolved from current state',()=>{const f=fixture();assert.equal(R.waypointCandidates(f.context(),'this point').length,3);f.selected='W2';assert.deepEqual(R.waypointCandidates(f.context(),'that waypoint'),['W2']);});
test('duplicate labels do not silently choose a waypoint',()=>{const f=fixture();f.plan.route.positions[0].label='Same';f.plan.route.positions[1].label='Same';assert.equal(R.resolveDecision(f.context(),{...move,waypointReference:'Same'},'new').command.type,'NEED_CLARIFICATION');});
test('invalid model outputs cannot introduce patches nonfinite numbers or unknown intents',()=>{for(const value of [null,{intent:'PATCH'},{...move,patch:{}},{...move,distanceValue:NaN},{...move,distanceValue:'2'}])assert.throws(()=>R.validateDecision(value));assert.equal(R.validateDecision({...move,absoluteXInches:null}).absoluteXInches,undefined);});
test('forward/back requires clarification and model delta arithmetic is rejected',()=>{const f=fixture();for(const direction of ['forward','back','up-stage'])assert.equal(R.resolveDecision(f.context(),{...move,direction},'new').command.type,'NEED_CLARIFICATION');assert.equal(R.resolveDecision(f.context(),{intent:'MOVE_WAYPOINT',waypointReference:'W2',deltaXInches:72,deltaYInches:0},'new').command.type,'NEED_CLARIFICATION');});
test('left/right/up/down use stage axes independently of camera',()=>{const c=fixture().context();for(const [direction,x,y] of [['left',-72,0],['right',72,0],['up',0,-72],['down',0,72]]){const d=R.resolveDecision(c,{...move,direction},'new').command.destination;assert.equal(d.deltaXInches,x);assert.equal(d.deltaYInches,y);}});
test('interpret then factual query then format uses current facts',async()=>{const f=fixture([{intent:'QUERY_DISTANCE'}]);await f.controller.initialize();await f.controller.send('How long is the route?');const format=f.mock.calls.find(c=>c.method==='format').request;assert.equal(format.facts.distanceInches,A.getRouteDistance(f.context()).distanceInches);assert.equal(f.state.timing.adapter,'mock');assert.deepEqual(f.mock.calls.map(c=>c.method),['availability','reset','create','interpret','format','reset']);});
test('bounded compact context excludes document and full fingerprint',()=>{const f=fixture();const c=T.compactContext('s',f.context()),json=JSON.stringify(c);assert.ok(json.length<1000);assert.equal(json.includes('schemaVersion'),false);assert.equal(c.revision.includes('objects'),false);assert.equal(c.waypointCount,3);});
test('model sessions compact each turn and reset on route changes',async()=>{const f=fixture([{intent:'QUERY_DISTANCE'},{intent:'QUERY_DISTANCE'}]);await f.controller.initialize();await f.controller.send('Distance?');f.h.document=H.record(f.h.document,{...f.h.document.present,plan:{...f.plan,route:{...f.plan.route,name:'Changed'}}});await f.controller.send('Now?');assert.equal(f.mock.calls.filter(c=>c.method==='create').length,2);const interpretations=f.mock.calls.filter(c=>c.method==='interpret');assert.notEqual(interpretations[0].request.context.revision,interpretations[1].request.context.revision);});
test('stage sessions reset on disposal with separate stage IDs',async()=>{const f=fixture();await f.controller.initialize();await f.controller.send('Distance?');f.controller.dispose();assert.equal(f.mock.calls.at(-1).method,'reset');const next=new RouteAIController(f.mock.adapter,'stage-other',f.context,()=>f.h,()=>{});await next.initialize();await next.send('Distance?');assert.ok(f.mock.calls.some(c=>c.method==='create'&&c.id.startsWith('stage-other-request-')));});
test('edit creates preview and ghost geometry without document mutation; cancel clears focus',async()=>{const f=fixture([move]),before=JSON.stringify(f.h);await f.controller.initialize();await f.controller.send('Move waypoint 2 two yards left');assert.equal(f.state.preview.proposedRoute.positions[1].position.x,78);assert.equal(JSON.stringify(f.h),before);assert.deepEqual(f.state.highlights.waypointIds,['W2']);f.controller.cancel();assert.equal(f.state.preview,undefined);assert.equal(f.state.highlights,undefined);});
test('Apply changes normal history and requires explicit Save; undo is preview-first',async()=>{const f=fixture([move,{intent:'UNDO'}]);await f.controller.initialize();await f.controller.send('Move');const applied=A.applyRoutePreview(f.state.preview,f.h);assert.equal(applied.status,'applied');assert.equal(applied.dirty,true);assert.equal(applied.requiresSave,true);f.h=applied.history;f.controller.applied(applied);assert.ok(f.state.messages.at(-1).text.includes('Save'));await f.controller.send('Undo that');assert.equal(f.state.preview.command.type,'UNDO_LAST_ASSISTANT_CHANGE');assert.equal(f.h.document.present.plan.route.positions[1].position.x,78);const undone=A.applyRoutePreview(f.state.preview,f.h);f.h=undone.history;f.controller.applied(undone);assert.equal(f.h.document.present.plan.route.positions[1].position.x,150);assert.match(f.state.messages.at(-1).text,/Reverted/);});
test('stale Apply is rejected by authoritative preview API',async()=>{const f=fixture([move]);await f.controller.initialize();await f.controller.send('Move');f.h.document=H.record(f.h.document,{...f.h.document.present,plan:{...f.plan,route:{...f.plan.route,name:'Other'}}});const applied=A.applyRoutePreview(f.state.preview,f.h);assert.equal(applied.code,'STALE_PREVIEW');f.controller.applied(applied);assert.match(f.state.error,/changed/);assert.ok(f.state.preview);});
test('clarification choice resumes original decision without another interpretation',async()=>{const f=fixture([{...move,waypointReference:'that waypoint'}]);await f.controller.initialize();await f.controller.send('Move that waypoint two yards left');assert.equal(f.state.clarification.options.length,3);await f.controller.choose('W2');assert.equal(f.state.preview.proposedRoute.positions[1].position.x,78);assert.equal(f.mock.calls.filter(c=>c.method==='interpret').length,1);});
test('clarification cannot resume against changed route',async()=>{const f=fixture([{...move,waypointReference:'that waypoint'}]);await f.controller.initialize();await f.controller.send('Move that');f.h.document=H.record(f.h.document,{...f.h.document.present,plan:{...f.plan,route:{...f.plan.route,name:'Changed'}}});await f.controller.choose('W2');assert.equal(f.state.preview,undefined);assert.match(f.state.error,/changed/);});
test('read-only required area and longest segment use existing query executor',async()=>{const f=fixture([{intent:'QUERY_AREAS'},{intent:'QUERY_LONGEST_SEGMENT'}]);await f.controller.initialize();await f.controller.send('Areas?');assert.equal(f.mock.calls.find(c=>c.method==='format').request.facts[0].id,'goal');await f.controller.send('Longest segment?');const facts=f.mock.calls.filter(c=>c.method==='format').at(-1).request.facts;assert.equal(facts.fromId,'W2');assert.equal(facts.toId,'W3');assert.deepEqual(f.state.highlights.routeSegmentIds,['W2->W3']);});
test('comparison resolves alternative ordinal from current solver facts',()=>{const f=fixture();f.solverResult=require('../src/planning/routeSolver/solveRoute.ts').solveRoute(f.context().solverInput);if(!f.solverResult.alternatives.length){assert.equal(R.resolveDecision(f.context(),{intent:'QUERY_COMPARISON',alternativeNumber:2},'new').command.type,'NEED_CLARIFICATION');}else{assert.equal(R.resolveDecision(f.context(),{intent:'QUERY_COMPARISON',alternativeNumber:1},'new').command.type,'COMPARE_ROUTE');}});
test('explicit avoidance rectangle calls solver and remains ephemeral after Apply',async()=>{const f=fixture([{intent:'REPLAN_AVOIDING_AREA',areaMinXInches:120,areaMinYInches:70,areaMaxXInches:180,areaMaxYInches:130}]);await f.controller.initialize();await f.controller.send('Avoid this rectangle');assert.ok(f.state.preview);assert.equal(f.state.preview.constraints.length,1);assert.equal(f.state.highlights.temporaryRegionIds.length,1);const applied=A.applyRoutePreview(f.state.preview,f.h);assert.equal(applied.status,'applied');assert.equal(JSON.stringify(applied.history.document.present.stage),JSON.stringify(f.stage));assert.equal(JSON.stringify(applied.history.document.present.plan).includes('temporaryRegionIds'),false);});
test('route change during interpretation cannot execute a stale decision',async()=>{const f=fixture([move]);let finish;f.mock.adapter.interpret=()=>new Promise(r=>{finish=r;});await f.controller.initialize();const pending=f.controller.send('Move');while(!finish)await new Promise(r=>setImmediate(r));f.h.document=H.record(f.h.document,{...f.h.document.present,plan:{...f.plan,route:{...f.plan.route,name:'changed'}}});finish(move);await pending;assert.equal(f.state.preview,undefined);assert.match(f.state.error,/changed/);});
test('concurrent sends are serialized',async()=>{const f=fixture([{intent:'QUERY_DISTANCE'}]);await f.controller.initialize();await Promise.all([f.controller.send('one'),f.controller.send('two')]);assert.equal(f.mock.calls.filter(c=>c.method==='interpret').length,1);});
for(const code of ['CONTEXT_SIZE','UNSUPPORTED_LANGUAGE','MODEL_REFUSAL','GENERATION_FAILED','NATIVE_BRIDGE_FAILED','INVALID_STRUCTURED_OUTPUT'])test('recoverable error '+code,async()=>{const f=fixture([new Error(code)]);await f.controller.initialize();await f.controller.send('Question');assert.ok(f.state.error);assert.equal(f.state.phase,'');assert.equal(f.state.preview,undefined);if(code==='CONTEXT_SIZE')assert.equal(f.mock.calls.at(-1).method,'reset');});
test('format failure retains valid proposal and exposes facts',async()=>{const f=fixture([move]);f.mock.adapter.format=async()=>{throw Error('GENERATION_FAILED');};await f.controller.initialize();await f.controller.send('Move');assert.ok(f.state.preview);assert.match(f.state.messages.at(-1).text,/Proposal ready/);assert.ok(f.state.details.includes('requiresApply'));});
test('unavailable production adapter never simulates responses',async()=>{const a=require('../src/planning/routeAI/adapter.ts').unavailableAdapter;assert.equal(await a.getAvailability(),'NATIVE_UNAVAILABLE');await assert.rejects(a.interpret('s',{}),/NATIVE_UNAVAILABLE/);});
function nativeAdapter(platform,bridge){
  const file=path.join(__dirname,'../src/planning/routeAI/nativeAdapter.ts');const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
  const module={exports:{}};new Function('require','module','exports',source)(id=>id==='react-native'?{Platform:{OS:platform}}:id==='expo-modules-core'?{requireOptionalNativeModule:()=>{if(bridge instanceof Error)throw bridge;return bridge;}}:require('../src/planning/routeAI/adapter.ts'),module,module.exports);return module.exports.productionAdapter();
}
test('web native wrapper never even loads a model bridge',async()=>{assert.equal(await nativeAdapter('web',new Error('must not call')).getAvailability(),'NATIVE_UNAVAILABLE');});
test('missing iOS native module is explicit unavailable',async()=>{assert.equal(await nativeAdapter('ios',null).getAvailability(),'NATIVE_UNAVAILABLE');});
test('bridge load failure cannot crash Route mode',async()=>{const f=fixture();f.controller=new RouteAIController(nativeAdapter('ios',new Error('bridge missing')),'s',f.context,()=>f.h,s=>{f.state=s;});await f.controller.initialize();assert.equal(f.state.availability,'NATIVE_UNAVAILABLE');assert.ok(f.state.details.includes('bridge missing'));});
test('native bridge malformed JSON becomes recoverable error',async()=>{const f=fixture();const bridge={getAvailability:async()=>'AVAILABLE',createSession:async()=>{},resetSession:async()=>{},interpret:async()=>'{',format:async()=>''};f.controller=new RouteAIController(nativeAdapter('ios',bridge),'s',f.context,()=>f.h,s=>{f.state=s;});await f.controller.initialize();await f.controller.send('Question');assert.ok(f.state.error);assert.equal(f.state.preview,undefined);});
test('add delete reorder replan and waypoint explanation map to existing commands',()=>{const c=fixture().context();for(const [d,type] of [[{intent:'ADD_WAYPOINT',absoluteXInches:100,absoluteYInches:80},'ADD_WAYPOINT'],[{intent:'DELETE_WAYPOINT',waypointReference:'W2'},'DELETE_WAYPOINT'],[{intent:'REORDER_WAYPOINT',waypointReference:'W3',secondWaypointReference:'W2'},'REORDER_WAYPOINT'],[{intent:'REPLAN'},'REPLAN'],[{intent:'QUERY_EXPLANATION',waypointReference:'W2'},'ANSWER_ONLY']])assert.equal(R.resolveDecision(c,d,'new').command.type,type);});
test('replan exposes existing solver duration independently of interpretation timing',async()=>{const f=fixture([{intent:'REPLAN'}]);await f.controller.initialize();await f.controller.send('Replan');assert.ok(f.state.timing.solverMs>=0);assert.ok(f.state.timing.assistantMs>=f.state.timing.solverMs);});
test('quick prompts are bounded and model instructions forbid invented geometry',()=>{assert.equal(quickPrompts.length,4);assert.match(T.instructions,/Never invent geometry/);});
test('Route AI sources have no network inference or production mock imports',()=>{
  const roots=['src/planning/routeAI','modules/route-ai'];const files=[];function walk(p){for(const e of fs.readdirSync(p,{withFileTypes:true})){if(e.name==='testing')continue;const full=path.join(p,e.name);if(e.isDirectory())walk(full);else if(/\.(ts|tsx|swift)$/.test(e.name))files.push(full);}}roots.forEach(r=>walk(path.join(__dirname,'..',r)));
  for(const file of files){const source=fs.readFileSync(file,'utf8');assert.equal(/\bfetch\s*\(|URLSession|axios|https?:\/\/|API_KEY|PrivateCloudCompute|testing\/mockAdapter/.test(source),false,file);}
});

const tick=()=>new Promise(r=>setImmediate(r));
async function until(predicate){for(let i=0;i<400&&!predicate();i++)await new Promise(r=>setTimeout(r,5));assert.ok(predicate());}
function hardened(f,options={}){f.controller=new RouteAIController(f.mock.adapter,'stage-s',f.context,()=>f.h,s=>{f.state=s;},'mock',options);return f;}
function change(f){f.h.document=H.record(f.h.document,{...f.h.document.present,plan:{...f.plan,route:{...f.plan.route,name:'changed'}}});}
for(const stop of ['cancel','dispose','background','close','invalidate'])test(stop+' during interpretation discards late result',async()=>{
 const f=fixture([move]);let finish;f.mock.adapter.interpret=()=>new Promise(r=>finish=r);await f.controller.initialize();const pending=f.controller.send('Move');await until(()=>finish);
 f.controller[stop]();const outcome=await pending;assert.equal(outcome.status,'cancelled');finish(move);await tick();assert.equal(f.state.preview,undefined);assert.equal(f.state.messages.filter(m=>m.status==='pending').length,0);
});
test('cancelled request cannot replace a newer response',async()=>{const f=fixture();let finish;const original=f.mock.adapter.interpret;f.mock.adapter.interpret=()=>new Promise(r=>finish=r);await f.controller.initialize();const old=f.controller.send('old');await until(()=>finish);f.controller.cancel();await old;f.mock.adapter.interpret=original;await f.controller.send('new');const before=JSON.stringify(f.state);finish(move);await tick();assert.equal(JSON.stringify(f.state),before);});
test('same-turn quick prompt and typed Send share ownership',async()=>{const f=fixture();await f.controller.initialize();await Promise.all([f.controller.send(quickPrompts[0]),f.controller.send('typed')]);assert.equal(f.state.messages.filter(m=>m.role==='You').length,1);assert.equal(f.mock.calls.filter(c=>c.method==='interpret').length,1);});
test('request IDs are stable within pipeline and unique between requests',async()=>{const f=fixture();await f.controller.initialize();await f.controller.send('first');await f.controller.send('second');const user=f.state.messages.filter(m=>m.role==='You');assert.notEqual(user[0].requestId,user[1].requestId);for(const m of user)assert.equal(f.state.messages.filter(n=>n.requestId===m.requestId).length,2);assert.equal(f.state.requestId,undefined);});
test('revision invalidation returns structured stale outcome',async()=>{const f=fixture();let finish;f.mock.adapter.interpret=()=>new Promise(r=>finish=r);await f.controller.initialize();const p=f.controller.send('old');await until(()=>finish);change(f);f.controller.contextChanged();assert.equal((await p).status,'stale');finish(move);assert.equal(f.controller.diagnostics.stale,1);});
test('stage identity changes invalidate even identical geometry',async()=>{const f=fixture();const context=f.context;let stageId='A',finish;f.context=()=>({...context(),stageId});f.controller=new RouteAIController(f.mock.adapter,'stage',f.context,()=>f.h,s=>f.state=s);f.mock.adapter.interpret=()=>new Promise(r=>finish=r);await f.controller.initialize();const p=f.controller.send('old');await until(()=>finish);stageId='B';finish(move);assert.equal((await p).status,'stale');assert.equal(f.state.preview,undefined);});
for(const boundary of ['interpret','format'])test(boundary+' timeout recovers and resets session',async()=>{const f=hardened(fixture(),{interpretMs:15,formatMs:15});const original=f.mock.adapter[boundary];f.mock.adapter[boundary]=()=>new Promise(()=>{});await f.controller.initialize();assert.equal((await f.controller.send('question')).status,'error');assert.match(f.state.error,/TOO LONG/);assert.equal(f.state.phase,'');assert.equal(f.mock.calls.at(-1).method,'reset');f.mock.adapter[boundary]=original;f.controller.options.interpretMs=2000;f.controller.options.formatMs=2000;await f.controller.retry();assert.equal(f.state.lifecycle,'IDLE');});
test('cancel during solving discards result and retains route',async()=>{const f=fixture([move]);let finish;hardened(f,{executor:()=>new Promise(r=>finish=r)});await f.controller.initialize();const before=JSON.stringify(f.h),p=f.controller.send('Move');await until(()=>finish);assert.equal(f.state.lifecycle,'SOLVING');f.controller.cancel();assert.equal((await p).status,'cancelled');finish(A.executeRouteAssistantCommand(f.context(),R.resolveDecision(f.context(),move,'late').command,f.h));await tick();assert.equal(JSON.stringify(f.h),before);assert.equal(f.state.preview,undefined);});
test('assistant operation timeout is controlled',async()=>{const f=hardened(fixture([move]),{operationMs:15,executor:()=>new Promise(()=>{})});await f.controller.initialize();await f.controller.send('Move');assert.equal(f.state.lifecycle,'ERROR');assert.match(f.state.error,/TOO LONG/);});
test('late formatter cannot publish a preview after cancellation',async()=>{const f=fixture([move]);let finish;f.mock.adapter.format=()=>new Promise(r=>finish=r);await f.controller.initialize();const p=f.controller.send('Move');await until(()=>finish);assert.equal(f.state.preview,undefined);f.controller.cancel();await p;finish('late');await tick();assert.equal(f.state.preview,undefined);});
test('preview blocks all new sends until explicitly dismissed',async()=>{const f=fixture([move,move]);await f.controller.initialize();await f.controller.send('Move');const id=f.state.preview.id;assert.equal((await f.controller.send('Move again')).status,'ignored');assert.equal(f.state.preview.id,id);f.controller.cancel();await f.controller.send('Move again');assert.ok(f.state.preview);});
test('Apply same-turn double tap calls host once',async()=>{const f=fixture([move]);await f.controller.initialize();await f.controller.send('Move');let count=0;const apply=p=>{count++;const result=A.applyRoutePreview(p,f.h);if(result.status==='applied')f.h=result.history;return result;};await Promise.all([f.controller.apply(apply),f.controller.apply(apply)]);assert.equal(count,1);assert.equal(f.state.preview,undefined);});
test('Apply rejects route change during its yield',async()=>{const f=fixture([move]);await f.controller.initialize();await f.controller.send('Move');let count=0;const p=f.controller.apply(()=>{count++;return {status:'applied'};});change(f);await p;assert.equal(count,0);assert.match(f.state.error,/changed/);});
test('stale Apply never calls host',async()=>{const f=fixture([move]);await f.controller.initialize();await f.controller.send('Move');change(f);let count=0;await f.controller.apply(()=>{count++;return {status:'applied'};});assert.equal(count,0);});
test('background clears unapplied preview without route changes',async()=>{const f=fixture([move]);await f.controller.initialize();const before=JSON.stringify(f.h);await f.controller.send('Move');f.controller.background();assert.equal(f.state.preview,undefined);assert.equal(JSON.stringify(f.h),before);});
test('native cancellation bridge receives the exact session ID',async()=>{const f=fixture();let finish,cancelled;f.mock.adapter.cancelGeneration=async id=>cancelled=id;f.mock.adapter.interpret=()=>new Promise(r=>finish=r);await f.controller.initialize();const p=f.controller.send('question');await until(()=>finish);const id=f.mock.calls.find(c=>c.method==='create').id;f.controller.cancel();await p;assert.equal(cancelled,id);});
test('fresh sessions and bounded recent turns recover after model error',async()=>{const f=fixture([new Error('CONTEXT_SIZE')]);await f.controller.initialize();await f.controller.send('fail');await f.controller.retry();for(let i=0;i<6;i++)await f.controller.send('again '+i);const calls=f.mock.calls.filter(c=>c.method==='interpret');assert.ok(calls.every(c=>c.request.recentMessages.length<=4));assert.equal(new Set(f.mock.calls.filter(c=>c.method==='create').map(c=>c.id)).size,calls.length);});
test('cache hits exact immutable input and isolates stage revision and constraints',()=>{const Cache=require('../src/planning/routeAssistant/solverCache.ts').AssistantSolverCache;const cache=new Cache(2),input=fixture().context().solverInput;const a=cache.solve('A:revision1',input);cache.solve('A:revision1',input);assert.equal(cache.diagnostics.hits,1);cache.solve('B:revision1',input);cache.solve('A:revision2',input);cache.solve('A:revision2',{...input,restrictedRegions:[{id:'temporary',polygon:[{x:120,y:70},{x:180,y:70},{x:180,y:130},{x:120,y:130}]}]});assert.equal(cache.diagnostics.misses,4);cache.solve('A:revision1',input);assert.equal(cache.diagnostics.misses,5);assert.ok(a.bestRoute);});
test('composer consumes authoritative lifecycle and production timing is hidden',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/planning/routeAI/RouteAISheet.tsx'),'utf8');assert.match(source,/isBusy\(state\)/);assert.match(source,/__DEV__/);assert.match(source,/maxHeight:100/);assert.match(source,/!!preview/);});
test('blank sends have no side effects',async()=>{const f=fixture();await f.controller.initialize();assert.equal((await f.controller.send('   ')).status,'ignored');assert.equal(f.state.messages.length,0);});

test('genuine replans reuse cache but stage changes do not',async()=>{const cache=require('../src/planning/routeAssistant/solverCache.ts').assistantSolverCache;cache.clear();const hits=cache.diagnostics.hits,misses=cache.diagnostics.misses;const f=fixture([{intent:'REPLAN'},{intent:'REPLAN'},{intent:'REPLAN'}]);const original=f.context;let stageId='A';f.context=()=>({...original(),stageId});hardened(f);await f.controller.initialize();await f.controller.send('Replan');f.controller.cancel();await f.controller.send('Replan');assert.equal(cache.diagnostics.hits,hits+1);assert.equal(f.state.timing.solverMs,0);f.controller.cancel();stageId='B';await f.controller.send('Replan');assert.equal(cache.diagnostics.misses,misses+2);});
test('Apply does not solve a genuine replan twice',async()=>{const f=fixture([{intent:'REPLAN'}]);await f.controller.initialize();await f.controller.send('Replan');const solve=require('../src/planning/routeSolver/solveRoute.ts');const original=solve.solveRoute;solve.solveRoute=()=>{throw Error('unexpected second solve');};try{assert.equal(A.applyRoutePreview(f.state.preview,f.h).status,'applied');}finally{solve.solveRoute=original;}});

test('multibyte context is compacted to the native bridge budget',()=>{const c=T.compactContext('stage',fixture().context());c.waypoints=Array.from({length:24},(_,i)=>({id:'W'+i,label:'??'.repeat(40),order:i}));const r=T.boundedInterpretation('??'.repeat(300),c,Array.from({length:4},()=>({role:'user',text:'??'.repeat(300)})));assert.ok(T.utf8Bytes(JSON.stringify(r))<=9000);assert.equal(c.waypoints.length,24);assert.equal(r.context.waypointCount,3);});

test('Apply rejects a preview from another stage even with identical route revision',async()=>{const f=fixture([move]);const original=f.context;let stageId='A';f.context=()=>({...original(),stageId});hardened(f);await f.controller.initialize();await f.controller.send('Move');stageId='B';let count=0;await f.controller.apply(()=>{count++;return {status:'applied'};});assert.equal(count,0);assert.match(f.state.error,/changed/);});
