const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,f);
const A=require('../src/planning/routeAssistant/index.ts');
const H=require('../src/editor/history.ts');
const {createPlan}=require('../src/planning/model.ts');
const {createRoute}=require('../src/planning/route.ts');
const {addSegment}=require('../src/stage/segments.ts');
const solver=require('../src/planning/routeSolver/solveRoute.ts');
const {candidateToStageRoute}=require('../src/planning/routeSolver/adoption.ts');
const p=(x,y)=>({x,y}), physical=(x,y)=>({space:'stage',x,y,z:0});
function fixture(required=false){
  const stage={schemaVersion:7,coordinateSystem:'inches',stage:{width:300,depth:240},objects:[{id:'start',type:'start',position:physical(20,100),rotation:0,geometry:{width:12,depth:12,height:0}}]};
  const plan=createPlan();plan.route=createRoute('r');
  plan.route.positions=[['W1',90,100],['W2',150,60],['W3',240,100]].map(([id,x,y])=>({id,label:id,position:physical(x,y),visibleTargetIds:[],engagedTargetIds:[]}));
  plan.route.engagementRules={...require('../src/planning/engagements.ts').defaultEngagementRules(),firingAreas:required?[{id:'a',vertices:[p(145,55),p(155,55),p(155,65),p(145,65)]}]:[{id:'goal',vertices:[p(235,95),p(245,95),p(245,105),p(235,105)]}]};
  return {stage,plan,c:A.createRouteAssistantContext(stage,plan),h:{document:H.history({stage,plan}),assistantChanges:[]}};
}
function run(f,type,payload={}){return A.executeRouteAssistantCommand(f.c,{type,sourceRevision:f.c.revision,...payload},f.h);}
const move={waypointId:'W2',destination:{kind:'delta',deltaXInches:-72,deltaYInches:0}};
test('assistant context is deeply immutable, detached, physical and viewport-free',()=>{const f=fixture();f.stage.viewport={zoom:7};f.plan.route.positions[0].position.x=5;assert.equal(f.c.route.positions[0].position.x,90);assert.ok(Object.isFrozen(f.c.route.positions[0].position));assert.equal(f.c.viewport,undefined);assert.equal(A.getRouteDistance(f.c).distanceInches,A.getRouteDistance(A.createRouteAssistantContext({...f.c.stage,viewport:{zoom:0.2}},f.c.plan)).distanceInches);});
test('read summary distance waypoints required areas alternatives diagnostics',()=>{const {c}=fixture();assert.equal(A.getRouteSummary(c).waypointCount,3);assert.equal(A.getWaypoint(c,'W2').position.x,150);assert.equal(A.getWaypoint(c,'bad'),null);assert.equal(A.getWaypoints(c).length,3);assert.equal(A.getRequiredAreas(c)[0].id,'goal');assert.deepEqual(A.getAlternatives(c),[]);assert.equal(A.getRouteDiagnostics(c),null);for(const type of ['SUMMARY','WAYPOINTS','DISTANCE','REQUIRED_AREAS','ALTERNATIVES','DIAGNOSTICS'])assert.equal(A.executeRouteAssistantCommand(c,{type:'ANSWER_ONLY',query:{type}}).kind,'answer');});
test('valid physical-inch delta move previews metrics without mutation',()=>{const f=fixture(),before=JSON.stringify(f),r=run(f,'MOVE_WAYPOINT',move);assert.equal(r.kind,'preview');assert.equal(r.preview.proposedRoute.positions[1].position.x,78);assert.equal(r.preview.valid,true);assert.equal(r.preview.delta.distanceDifferenceInches,r.preview.after.distanceInches-r.preview.before.distanceInches);assert.equal(JSON.stringify(f),before);assert.ok(r.durationMs>=0);});
test('absolute move',()=>{const r=run(fixture(),'MOVE_WAYPOINT',{waypointId:'W2',destination:{kind:'absolute',position:p(100,80)}});assert.equal(r.preview.proposedRoute.positions[1].position.y,80);});
test('invalid waypoint',()=>{assert.equal(run(fixture(),'MOVE_WAYPOINT',{...move,waypointId:'bad'}).code,'WAYPOINT_NOT_FOUND');});
test('invalid finite coordinate and outside boundary',()=>{for(const x of [NaN,Infinity])assert.equal(run(fixture(),'MOVE_WAYPOINT',{waypointId:'W1',destination:{kind:'absolute',position:p(x,10)}}).code,'INVALID_COORDINATE');assert.equal(run(fixture(),'MOVE_WAYPOINT',{waypointId:'W1',destination:{kind:'absolute',position:p(-1,10)}}).code,'OUTSIDE_STAGE');});
for(const kind of ['before','after'])test(`add ${kind} reference`,()=>{const r=run(fixture(),'ADD_WAYPOINT',{waypointId:'new',position:p(100,90),placement:{kind,waypointId:'W2'}});assert.equal(r.kind,'preview');assert.equal(r.preview.proposedRoute.positions[kind==='before'?1:2].id,'new');});
test('add between and nearest segment uses explicit inches',()=>{for(const placement of [{kind:'between',fromId:'W1',toId:'W2'},{kind:'nearest'}]){const r=run(fixture(),'ADD_WAYPOINT',{waypointId:'new',position:p(110,85),placement});assert.equal(r.preview.proposedRoute.positions[1].id,'new');assert.equal(r.preview.proposedRoute.positions[1].position.x,110);}});
test('add invalid reference duplicate ID and nonadjacent segment rejected',()=>{const f=fixture();for(const placement of [{kind:'before',waypointId:'bad'},{kind:'between',fromId:'W1',toId:'W3'}])assert.equal(run(f,'ADD_WAYPOINT',{waypointId:'new',position:p(100,80),placement}).kind,'error');assert.equal(run(f,'ADD_WAYPOINT',{waypointId:'W1',position:p(100,80),placement:{kind:'nearest'}}).code,'DUPLICATE_WAYPOINT_ID');});
test('delete previews route impact',()=>{const r=run(fixture(),'DELETE_WAYPOINT',{waypointId:'W2'});assert.equal(r.preview.delta.waypointDifference,-1);assert.ok(r.preview.delta.distanceDifferenceInches<0);assert.equal(r.preview.valid,true);});
test('delete required-area waypoint is previewed invalid and cannot apply',()=>{const f=fixture(true),r=run(f,'DELETE_WAYPOINT',{waypointId:'W2'});assert.equal(r.preview.valid,false);assert.deepEqual(r.preview.delta.coverageLost,['a']);assert.ok(r.preview.warnings.includes('REQUIRED_AREAS_MISSED'));assert.equal(A.applyRoutePreview(r.preview,f.h).code,'INVALID_ROUTE_GEOMETRY');});
test('reorder valid and invalid',()=>{const f=fixture(),r=run(f,'REORDER_WAYPOINT',{waypointId:'W3',beforeId:'W2'});assert.deepEqual(r.preview.proposedRoute.positions.map(p=>p.id),['W1','W3','W2']);assert.equal(r.preview.delta.geometryChanges.reordered,true);assert.equal(run(f,'REORDER_WAYPOINT',{waypointId:'W2',beforeId:'W2'}).code,'INVALID_REORDER');assert.equal(run(f,'REORDER_WAYPOINT',{waypointId:'bad',beforeId:'W2'}).code,'WAYPOINT_NOT_FOUND');});
test('replan calls authoritative solver deterministically',()=>{const f=fixture();const original=solver.solveRoute;let calls=0;solver.solveRoute=i=>{calls++;return original(i);};try{const a=run(f,'REPLAN'),b=run(f,'REPLAN');assert.equal(calls,2);assert.deepEqual(a.preview.proposedRoute,b.preview.proposedRoute);assert.deepEqual(a.preview.proposedRoute,candidateToStageRoute(original(f.c.solverInput).bestRoute,f.plan));}finally{solver.solveRoute=original;}});
test('avoidance changes solver route without modifying stage or persisting region',()=>{const f=fixture(),before=JSON.stringify(f.stage),plain=run(f,'REPLAN'),r=run(f,'REPLAN_AVOIDING_AREA',{area:{id:'temporary',polygon:[p(120,70),p(180,70),p(180,130),p(120,130)]}});assert.equal(r.kind,'preview');assert.ok(r.preview.after.distanceInches>plain.preview.after.distanceInches);assert.equal(JSON.stringify(f.stage),before);assert.deepEqual(r.highlights.temporaryRegionIds,['temporary']);const applied=A.applyRoutePreview(r.preview,f.h);assert.equal(applied.status,'applied');assert.equal(JSON.stringify(applied.history.document.present.stage),before);assert.equal(JSON.stringify(applied.history.document.present.plan).includes('temporary'),false);});
test('invalid avoidance and no-start solver intake return structured failures',()=>{const f=fixture();assert.equal(run(f,'REPLAN_AVOIDING_AREA',{area:{id:'bad',polygon:[p(1,1)]}}).code,'INVALID_AVOIDANCE_AREA');f.stage.objects=[];f.c=A.createRouteAssistantContext(f.stage,f.plan);assert.equal(run(f,'REPLAN').code,'INVALID_SOLVER_INPUT');});
test('apply changes editable route normal history dirty state and requires explicit Save',()=>{const f=fixture(),r=run(f,'MOVE_WAYPOINT',move),a=A.applyRoutePreview(r.preview,f.h);assert.equal(a.status,'applied');assert.equal(a.dirty,true);assert.equal(a.requiresSave,true);assert.equal(a.history.document.past.length,1);assert.equal(a.history.document.present.plan.route.positions[1].position.x,78);assert.equal(f.h.document.present.plan.route.positions[1].position.x,150);assert.deepEqual(H.undo(a.history.document).present,f.h.document.present);});
test('stale route or stage preview rejected',()=>{for(const stageEdit of [false,true]){const f=fixture(),r=run(f,'MOVE_WAYPOINT',move),next=A.clone(f.h.document.present);if(stageEdit)next.stage.stage.width=400;else next.plan.route.positions[0].position.x++;f.h.document=H.record(f.h.document,next);assert.equal(A.applyRoutePreview(r.preview,f.h).code,'STALE_PREVIEW');}assert.equal(run(fixture(),'MOVE_WAYPOINT',{...move,sourceRevision:'old'}).code,'STALE_REVISION');});
test('tampered preview cannot alter arbitrary StagePlan route',()=>{const f=fixture(),r=run(f,'MOVE_WAYPOINT',move),fake=A.clone(r.preview);fake.proposedRoute.positions[0].position.x=42;assert.equal(A.applyRoutePreview(fake,f.h).code,'INVALID_PREVIEW');});
test('assistant undo previews then uses existing history undo',()=>{const f=fixture(),applied=A.applyRoutePreview(run(f,'MOVE_WAYPOINT',move).preview,f.h);f.h=applied.history;f.c=A.createRouteAssistantContext(f.stage,f.h.document.present.plan);const r=run(f,'UNDO_LAST_ASSISTANT_CHANGE');assert.equal(r.kind,'preview');const a=A.applyRoutePreview(r.preview,f.h);assert.equal(a.status,'applied');assert.deepEqual(a.history.document.present.plan,f.plan);assert.equal(a.history.document.future.length,1);});
test('assistant undo refuses intervening manual edits; restore remains preview-first',()=>{const f=fixture(),a=A.applyRoutePreview(run(f,'MOVE_WAYPOINT',move).preview,f.h);f.h=a.history;const next=A.clone(f.h.document.present);next.plan.route.positions[0].position.y=95;f.h.document=H.record(f.h.document,next);f.c=A.createRouteAssistantContext(f.stage,next.plan);assert.equal(run(f,'UNDO_LAST_ASSISTANT_CHANGE').code,'NO_PREVIOUS_ROUTE');assert.equal(run(f,'RESTORE_PREVIOUS_ROUTE').kind,'preview');});
test('comparison includes geometry count direction and coverage changes',()=>{const f=fixture(true),b=A.clone(f.c.route);b.positions.splice(1,1);const r=A.compareRoutes(f.c,f.c.route,b);assert.equal(r.waypointDifference,-1);assert.deepEqual(r.coverageLost,['a']);assert.deepEqual(r.geometryChanges.removed,['W2']);assert.ok(r.directionChangeDifference<0);assert.equal(A.executeRouteAssistantCommand(f.c,{type:'COMPARE_ROUTE',routeA:f.plan.route,routeB:b}).kind,'comparison');});
test('deterministic wall explanation and valid highlight IDs',()=>{const f=fixture();f.stage=addSegment(f.stage,'wall','wall',physical(130,40),physical(130,160)).stage;let c=A.createRouteAssistantContext(f.stage,f.plan);const result=solver.solveRoute(c.solverInput);f.plan.route=candidateToStageRoute(result.bestRoute,f.plan);c=A.createRouteAssistantContext(f.stage,f.plan,{solverResult:result});let found=false;for(const w of c.route.positions){const facts=A.explainWaypoint(c,w.id);assert.deepEqual(facts,A.explainWaypoint(c,w.id));if(facts.reasons.some(r=>r.type==='OBSTACLE_DETOUR')){found=true;assert.equal(facts.removable,false);const r=A.executeRouteAssistantCommand(c,{type:'ANSWER_ONLY',query:{type:'EXPLAIN_WAYPOINT',waypointId:w.id}});assert.ok(r.highlights.stageObjectIds.includes('wall'));for(const id of r.highlights.stageObjectIds)assert.ok(c.stage.objects.some(o=>o.id===id));for(const id of r.highlights.requiredAreaIds)assert.ok(c.solverInput.requiredAreas.some(a=>a.id===id));assert.ok(A.formatExplanation(facts.reasons).includes('OBSTACLE_DETOUR'));}}assert.ok(found);assert.ok(A.getBlockingGeometry(c,p(20,100),p(240,100)).stageObjectIds.includes('wall'));assert.equal(A.getAlternatives(c).length,result.alternatives.length);assert.ok(A.getRouteDiagnostics(c));});
test('segment query validates adjacency and returns focus',()=>{const f=fixture();assert.equal(A.explainRouteSegment(f.c,'W1','W3').code,'SEGMENT_NOT_FOUND');const r=A.executeRouteAssistantCommand(f.c,{type:'ANSWER_ONLY',query:{type:'EXPLAIN_SEGMENT',fromId:'START',toId:'W1'}});assert.deepEqual(r.highlights.routeSegmentIds,['START->W1']);});
test('ambiguous waypoint requires clarification; selected ID resolves explicitly',()=>{const f=fixture(),r=run(f,'MOVE_WAYPOINT',{...move,waypointId:null});assert.equal(r.kind,'clarification');assert.equal(r.data.options.length,3);f.c=A.createRouteAssistantContext(f.stage,f.plan,{selectedWaypointId:'W2'});assert.equal(run(f,'MOVE_WAYPOINT',{...move,waypointId:null}).kind,'preview');assert.equal(A.executeRouteAssistantCommand(f.c,{type:'NEED_CLARIFICATION',question:'Which area?',options:[{id:'a',label:'Area A'}]}).kind,'clarification');});
test('untrusted commands reject arbitrary patches extra fields and malformed payloads',()=>{const f=fixture();for(const command of [null,{type:'PATCH',patch:{}},{type:'MOVE_WAYPOINT',sourceRevision:f.c.revision,...move,patch:{}},{type:'ADD_WAYPOINT',sourceRevision:f.c.revision},{type:'ANSWER_ONLY',query:{type:'DISTANCE',patch:{}}}])assert.equal(A.executeRouteAssistantCommand(f.c,command).code,'INVALID_COMMAND');});

