const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,f);
const {solveRoute}=require('../src/planning/routeSolver/solveRoute.ts');
const {stageGeometry}=require('../src/planning/routeSolver/stageGeometry.ts');
const T=require('../src/planning/routeSolver/traversability.ts');
const {reduceWaypoints}=require('../src/planning/routeSolver/scoring.ts');
const {candidateToStageRoute,solverInputFromPlan}=require('../src/planning/routeSolver/adoption.ts');
const {createPlan}=require('../src/planning/model.ts');
const {isStageRoute,movePosition,reorderPosition}=require('../src/planning/route.ts');
const {addSegment}=require('../src/stage/segments.ts');
const p=(x,y)=>({x,y});
const physical=(x,y)=>({space:'stage',x,y,z:0});
const area=(id,x,y,w=20,h=20)=>({id,polygon:[p(x,y),p(x+w,y),p(x+w,y+h),p(x,y+h)]});
const exact=(id,x,y)=>({id,polygon:[p(x,y)]});
function input(areas=[exact('goal',180,100)]){return {stage:{schemaVersion:7,coordinateSystem:'inches',stage:{width:240,depth:200},objects:[]},start:p(20,100),requiredAreas:areas,options:{maxAlternatives:0}};}
function wall(i,a=physical(100,40),b=physical(100,160)){i.stage=addSegment(i.stage,'wall','wall',a,b).stage;return i;}
function diag(){return solveRoute(input([])).diagnostics;}
function faults(points,gap=0){let i=input([]);for(let j=1;j<points.length;j++){const a=points[j-1],b=points[j];i.stage=addSegment(i.stage,'faultLine',`f${j}`,physical(a.x+(j===1?gap:0),a.y),physical(b.x,b.y)).stage;}return i;}
function geometry(i){return stageGeometry(i,diag());}
function valid(i,r){assert.equal(r.status,'success');const g=geometry(i);r.bestRoute.waypoints.slice(1).forEach((b,j)=>assert.ok(T.isSegmentTraversable(r.bestRoute.waypoints[j],b,g)));assert.equal(r.bestRoute.requiredAreasMissed.length,0);}
test('straight unobstructed route uses physical distance',()=>{const i=input(),r=solveRoute(i);valid(i,r);assert.equal(r.bestRoute.totalDistanceInches,160);assert.equal(r.bestRoute.waypointCount,1);});
test('wall detour cannot cross solid footprint and explains corners',()=>{const i=wall(input()),r=solveRoute(i);valid(i,r);assert.ok(r.bestRoute.totalDistanceInches>160);assert.ok(r.bestRoute.waypointCount>=3);assert.ok(r.bestRoute.explanationData.some(e=>e.barrierIds?.includes('wall')));});
test('stage boundaries reject outside start and outside goals',()=>{const i=input();i.start=p(-1,10);assert.equal(solveRoute(i).status,'invalid-input');assert.equal(solveRoute(input([exact('outside',250,100)])).status,'unreachable');});
test('required polygon chooses near boundary rather than preferred center',()=>{const i=input([area('a',100,90)]);i.requiredAreas[0].preferredPoint=p(110,100);const r=solveRoute(i);assert.equal(r.bestRoute.totalDistanceInches,80);assert.deepEqual(r.bestRoute.requiredAreasVisited,['a']);});
test('multiple required regions are all visited',()=>{const i=input([area('a',80,20),area('b',150,140),area('c',200,20)]),r=solveRoute(i);valid(i,r);assert.equal(r.bestRoute.requiredAreasVisited.length,3);});
test('ordering is independent of caller creation order',()=>{const i=input([exact('far',180,100),exact('near',70,100)]),a=solveRoute(i);i.requiredAreas.reverse();const b=solveRoute(i);assert.deepEqual(a.bestRoute.waypoints,b.bestRoute.waypoints);assert.equal(a.bestRoute.totalDistanceInches,160);});
test('reduction removes collinear noise while preserving traversability and coverage',()=>{const i=input(),g=geometry(i),d=diag();assert.deepEqual(reduceWaypoints([i.start,p(50,100),p(80,100),p(180,100)],g,d),[i.start,p(180,100)]);assert.equal(d.waypointReductions,2);});
test('overlapping required polygons share a single visit',()=>{const i=input([area('a',80,90,50,30),area('b',100,90,50,30)]),r=solveRoute(i);valid(i,r);assert.equal(r.bestRoute.waypointCount,1);assert.equal(r.bestRoute.totalDistanceInches,80);});
test('unreachable required region returns structured failure',()=>{const i=wall(input(),physical(100,0),physical(100,200)),r=solveRoute(i);assert.equal(r.status,'unreachable');assert.equal(r.bestRoute,null);assert.deepEqual(r.diagnostics.unresolvedRequiredAreas,['goal']);});
const rectangle=[p(40,40),p(140,40),p(140,140),p(40,140),p(40,40)];
test('slightly separated fault endpoints merge without changing stage',()=>{const i=faults(rectangle,1),before=JSON.stringify(i.stage),r=solveRoute(i);assert.equal(r.diagnostics.interpretedFaultRegionCount,1);assert.ok(r.diagnostics.endpointMerges>0);assert.equal(JSON.stringify(i.stage),before);});
test('small fault gap closes with explicit diagnostic',()=>{const i=faults(rectangle,3),r=solveRoute(i);assert.equal(r.diagnostics.interpretedFaultRegionCount,1);assert.ok(r.diagnostics.inferredGapClosures>0);});
test('large gap stays open and warns',()=>{const i=faults(rectangle,12),r=solveRoute(i);assert.equal(r.diagnostics.interpretedFaultRegionCount,0);assert.ok(geometry(i).openFaultBoundaries.length);assert.ok(r.diagnostics.warnings.some(w=>w.includes('Open fault')));});
test('irregular enclosed fault polygon is detected',()=>{const i=faults([p(20,20),p(90,28),p(140,90),p(70,160),p(30,85),p(20,20)]);assert.equal(solveRoute(i).diagnostics.interpretedFaultRegionCount,1);});
test('T junction splits two enclosed faces',()=>{let i=faults(rectangle);i.stage=addSegment(i.stage,'faultLine','divider',physical(90,40),physical(90,140)).stage;assert.equal(solveRoute(i).diagnostics.interpretedFaultRegionCount,2);});
test('raw immutable document and input stay untouched',()=>{const i=wall(input()),before=JSON.stringify(i);Object.freeze(i.start);Object.freeze(i.stage.objects);Object.freeze(i.stage);solveRoute(i);assert.equal(JSON.stringify(i),before);});
test('viewport pan is excluded from physical solver',()=>{const i=input(),a=solveRoute({...i,viewport:{panX:200,panY:300}});assert.deepEqual(a.bestRoute,solveRoute(i).bestRoute);});
test('repeated solving has deterministic route and search diagnostics',()=>{const i=wall(input()),a=solveRoute(i),b=solveRoute(i);assert.deepEqual(a.bestRoute,b.bestRoute);delete a.diagnostics.solveDurationMs;delete b.diagnostics.solveDurationMs;assert.deepEqual(a.diagnostics,b.diagnostics);});
test('different zoom levels return identical coordinates',()=>{const i=input();assert.deepEqual(solveRoute({...i,zoom:0.25}).bestRoute.waypoints,solveRoute({...i,zoom:8}).bestRoute.waypoints);});
test('alternatives have meaningfully different traversable geometry',()=>{const i=wall(input());i.options.maxAlternatives=2;const r=solveRoute(i);valid(i,r);assert.ok(r.alternatives.length>0);for(const a of r.alternatives){assert.notDeepEqual(a.waypoints,r.bestRoute.waypoints);assert.ok(a.waypoints.some(q=>r.bestRoute.waypoints.every(p=>T.distanceBetweenPoints(p,q)>6)));a.waypoints.slice(1).forEach((p,j)=>assert.ok(T.isSegmentTraversable(a.waypoints[j],p,geometry(i))));}});
test('one best route is returned without artificial alternatives on clear stage',()=>{const i=input();i.options.maxAlternatives=2;const r=solveRoute(i);assert.ok(r.bestRoute);assert.equal(r.alternatives.length,0);assert.equal(Array.isArray(r.bestRoute),false);});
test('legacy style preferences cannot change new solver',()=>{const i=input(),r=solveRoute(i);for(const style of ['BALANCED','PERSONALIZED','MORE_MOVEMENT_EASIER_SHOOTING'])assert.deepEqual(solveRoute({...i,style,backwardMovement:'AVOID',profile:{movementSpeed:1}}).bestRoute,r.bestRoute);});
test('adoption converts into detached editable ordinary StageRoute',()=>{const i=input([exact('a',70,50),exact('b',180,100)]),r=solveRoute(i),plan=createPlan(),route=candidateToStageRoute(r.bestRoute,plan);assert.ok(isStageRoute(route));const before=JSON.stringify(r);const moved=movePosition(route,route.positions[0].id,physical(80,60),i.stage.stage);assert.equal(moved.positions[0].position.x,80);assert.equal(reorderPosition(moved,moved.positions[0].id,1).positions[1].id,moved.positions[0].id);assert.equal(JSON.stringify(r),before);});
test('plan intake uses existing firing areas, falls back to mandatory points',()=>{const i=input(),plan=createPlan();i.stage.objects=[{id:'start',type:'start',position:physical(20,100),rotation:0,geometry:{width:12,depth:12,height:0}}];plan.route=candidateToStageRoute(solveRoute(i).bestRoute,plan);assert.equal(solverInputFromPlan(i.stage,plan).requiredAreas[0].polygon.length,1);plan.route.engagementRules={firingAreas:[{id:'region',vertices:area('region',50,50).polygon}]};assert.equal(solverInputFromPlan(i.stage,plan).requiredAreas[0].id,'region');});
test('fault lines do not block movement',()=>{const i=faults(rectangle);i.requiredAreas=[exact('goal',180,100)];assert.equal(solveRoute(i).bestRoute.totalDistanceInches,160);});
test('restricted geometry and positive clearance are enforced',()=>{const i=input();i.restrictedRegions=[{id:'restricted',polygon:area('r',95,40,10,120).polygon}];i.options.clearanceInches=2;valid(i,solveRoute(i));assert.ok(solveRoute(i).bestRoute.totalDistanceInches>160);});
test('search and graph budgets produce structured limits',()=>{const i=input();i.options.maxSearchIterations=0;assert.equal(solveRoute(i).status,'limit');i.options.maxSearchIterations=10000;i.options.maxNodes=1;assert.equal(solveRoute(i).status,'limit');});
test('large area count uses bounded deterministic optimized ordering',()=>{const i=input(Array.from({length:10},(_,j)=>exact(`a${j}`,30+j*15,100)));const r=solveRoute(i);valid(i,r);assert.ok(r.diagnostics.warnings.some(w=>w.includes('2-opt')));assert.equal(r.bestRoute.totalDistanceInches,145);});
test('dangling T branch stays an open boundary alongside enclosed face',()=>{let i=faults(rectangle);i.stage=addSegment(i.stage,'faultLine','branch',physical(90,40),physical(90,15)).stage;const g=geometry(i);assert.equal(g.faultRegions.length,1);assert.equal(g.openFaultBoundaries.length,1);});
test('duplicate and overlapping fault pieces do not duplicate regions',()=>{let i=faults(rectangle);i.stage=addSegment(i.stage,'faultLine','overlap',physical(60,40),physical(120,40)).stage;assert.equal(solveRoute(i).diagnostics.interpretedFaultRegionCount,1);});
test('crooked near T junction is connected deterministically',()=>{let i=faults(rectangle);i.stage=addSegment(i.stage,'faultLine','divider',physical(90,41),physical(92,139)).stage;assert.equal(solveRoute(i).diagnostics.interpretedFaultRegionCount,2);});
test('restricted travel union prevents a shortcut across a concave missing region',()=>{const i=input([exact('goal',120,60)]);i.start=p(20,60);i.allowedTravelRegions=[[p(0,0),p(140,0),p(140,80),p(100,80),p(100,20),p(40,20),p(40,80),p(0,80)]];const r=solveRoute(i);valid(i,r);assert.ok(r.bestRoute.totalDistanceInches>100);});
test('invalid geometry fails without a thrown exception',()=>{const i=wall(input());i.stage.objects[0].rotation=NaN;assert.equal(solveRoute(i).status,'invalid-input');i.stage.objects[0].rotation=0;i.requiredAreas[0].polygon[0].x=Infinity;assert.equal(solveRoute(i).status,'invalid-input');});
test('clear polygon route does not generate arbitrary variety',()=>{const i=input([area('a',180,90)]);i.options.maxAlternatives=2;assert.equal(solveRoute(i).alternatives.length,0);});
test('single-goal A star returns deterministic wall detour',()=>{const {navigationGraph}=require('../src/planning/routeSolver/navigationGraph.ts');const {shortestPath}=require('../src/planning/routeSolver/shortestPath.ts');const i=wall(input()),g=geometry(i),d=diag(),graph=navigationGraph(g,512,d),goal=graph.nodes.findIndex(q=>T.distanceBetweenPoints(q,p(180,100))<1e-7);const path=shortestPath(graph,0,goal,d,10000);assert.ok(path.distance>160);path.path.slice(1).forEach((j,k)=>assert.ok(T.isSegmentTraversable(graph.nodes[path.path[k]],graph.nodes[j],g)));});
test('future explanation queries expose factual physical differences',()=>{const Q=require('../src/planning/routeSolver/index.ts');const a=solveRoute(input()).bestRoute,b=solveRoute(wall(input())).bestRoute;assert.equal(Q.getRouteSummary(a).totalDistanceInches,160);assert.ok(Q.compareRoutes(a,b).distanceDifferenceInches<0);assert.ok(Q.explainWaypoint(b,1).some(e=>e.kind==='obstruction'));});
test('symmetric equal-cost region order remains independent of creation order',()=>{const i=input([exact('a',80,50),exact('b',80,150),exact('c',180,100)]),a=solveRoute(i);i.requiredAreas.reverse();assert.deepEqual(solveRoute(i).bestRoute,a.bestRoute);});
